/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(add_preamble.h) */
/* BINDTOOL_HEADER_FILE_HASH(4ad715768f31adda8a9381d358770297) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/add_preamble.h>
// pydoc.h is automatically generated in the build directory
#include <add_preamble_pydoc.h>

void bind_add_preamble(py::module &m) {

  using add_preamble = ::gr::ncjt::add_preamble;

  py::class_<add_preamble, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<add_preamble>>(m, "add_preamble", D(add_preamble))

      .def(py::init(&add_preamble::make), py::arg("nstrm"), py::arg("filename"),
           py::arg("delay"), py::arg("debug"), D(add_preamble, make))

      ;
}
