/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(add_ctrldata.h) */
/* BINDTOOL_HEADER_FILE_HASH(ca3258b8530130daccf8c48eed989c29) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/add_ctrldata.h>
// pydoc.h is automatically generated in the build directory
#include <add_ctrldata_pydoc.h>

void bind_add_ctrldata(py::module &m) {

  using add_ctrldata = ::gr::ncjt::add_ctrldata;

  py::class_<add_ctrldata, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<add_ctrldata>>(m, "add_ctrldata", D(add_ctrldata))

      .def(py::init(&add_ctrldata::make), py::arg("nstrm"),
           py::arg("ctrl_datalen"), py::arg("add_txseq"), py::arg("add_rxseq"),
           py::arg("add_llr"), py::arg("debug") = false, D(add_ctrldata, make))

      ;
}
