/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(burst_tx.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c3542f2055b29b77e91cb43e6d485d21) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/burst_tx.h>
// pydoc.h is automatically generated in the build directory
#include <burst_tx_pydoc.h>

void bind_burst_tx(py::module &m) {

  using burst_tx = ::gr::ncjt::burst_tx;

  py::class_<burst_tx, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<burst_tx>>(m, "burst_tx", D(burst_tx))

      .def(py::init(&burst_tx::make), py::arg("filename"),
           py::arg("samplerate"), py::arg("pktspersec"), py::arg("pktsize"),
           py::arg("starttime"), py::arg("debug"), D(burst_tx, make))

      ;
}
