/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(check_ctrldata.h) */
/* BINDTOOL_HEADER_FILE_HASH(6f7ae479d607e9201df83081055aea2d) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/check_ctrldata.h>
// pydoc.h is automatically generated in the build directory
#include <check_ctrldata_pydoc.h>

void bind_check_ctrldata(py::module &m) {

  using check_ctrldata = ::gr::ncjt::check_ctrldata;

  py::class_<check_ctrldata, gr::tagged_stream_block, gr::block,
             gr::basic_block, std::shared_ptr<check_ctrldata>>(
      m, "check_ctrldata", D(check_ctrldata))

      .def(py::init(&check_ctrldata::make), py::arg("nstrm"),
           py::arg("ctrl_datalen"), py::arg("has_txseq"), py::arg("has_rxseq"),
           py::arg("has_llr"), py::arg("extract_llr"), py::arg("waitrdy"),
           py::arg("debug") = false, D(check_ctrldata, make))

      ;
}
