/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(csi_fb_processing.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fbfb8e7f06ce7eab66aeba4ab563439d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/csi_fb_processing.h>
// pydoc.h is automatically generated in the build directory
#include <csi_fb_processing_pydoc.h>

void bind_csi_fb_processing(py::module& m)
{

    using csi_fb_processing    = gr::ncjt::csi_fb_processing;


    py::class_<csi_fb_processing, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<csi_fb_processing>>(m, "csi_fb_processing", D(csi_fb_processing))

        .def(py::init(&csi_fb_processing::make),
           D(csi_fb_processing,make)
        )
        



        ;




}








