/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(dual_tx_ctrl.h) */
/* BINDTOOL_HEADER_FILE_HASH(9234e70987847f3650a437dd184f6ef9) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/dual_tx_ctrl.h>
// pydoc.h is automatically generated in the build directory
#include <dual_tx_ctrl_pydoc.h>

void bind_dual_tx_ctrl(py::module &m) {

  using dual_tx_ctrl = ::gr::ncjt::dual_tx_ctrl;

  py::class_<dual_tx_ctrl, gr::block, gr::basic_block,
             std::shared_ptr<dual_tx_ctrl>>(m, "dual_tx_ctrl", D(dual_tx_ctrl))

      .def(py::init(&dual_tx_ctrl::make), py::arg("ntx"), py::arg("samplerate"),
           py::arg("pktspersec"), py::arg("framelen1"), py::arg("beaconfile1"),
           py::arg("starttime1"), py::arg("framelen2"), py::arg("beaconfile2"),
           py::arg("starttime2"), py::arg("padding"), py::arg("autostart"),
           py::arg("debug"), D(dual_tx_ctrl, make))

      ;
}
