/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(gnb_sync.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1f4cdb673ae4cd590a349ecfde7e81cf) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/gnb_sync.h>
// pydoc.h is automatically generated in the build directory
#include <gnb_sync_pydoc.h>

void bind_gnb_sync(py::module &m) {

  using gnb_sync = ::gr::ncjt::gnb_sync;

  py::class_<gnb_sync, gr::block, gr::basic_block, std::shared_ptr<gnb_sync>>(
      m, "gnb_sync", D(gnb_sync))

      .def(py::init(&gnb_sync::make), py::arg("nchans"),
           py::arg("npreamblesyms"), py::arg("ndatasyms"),
           py::arg("sampling_freq"), py::arg("pktspersec"),
           py::arg("acorr_thrd"), py::arg("xcorr_thrd"),
           py::arg("max_corr_len"), py::arg("debug"), D(gnb_sync, make))

      ;
}
