/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(ltf_chanest.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5590bc8223f7dfe6ae19558dbcf58907) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/ltf_chanest.h>
// pydoc.h is automatically generated in the build directory
#include <ltf_chanest_pydoc.h>

void bind_ltf_chanest(py::module &m) {

  using ltf_chanest = ::gr::ncjt::ltf_chanest;

  py::class_<ltf_chanest, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<ltf_chanest>>(m, "ltf_chanest", D(ltf_chanest))

      .def(py::init(&ltf_chanest::make), py::arg("fftsize"), py::arg("ntx"),
           py::arg("nrx"), py::arg("npreamblesyms"), py::arg("ndatasyms"),
           py::arg("csifb"), py::arg("logfreq") = 10, py::arg("debug") = false,
           D(ltf_chanest, make))

      ;
}
