/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(mapper_muxer_phase3.h) */
/* BINDTOOL_HEADER_FILE_HASH(7702dd21bb476042a821744ab2499d38) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/mapper_muxer_phase3.h>
// pydoc.h is automatically generated in the build directory
#include <mapper_muxer_phase3_pydoc.h>

void bind_mapper_muxer_phase3(py::module &m) {

  using mapper_muxer_phase3 = ::gr::ncjt::mapper_muxer_phase3;

  py::class_<mapper_muxer_phase3, gr::tagged_stream_block, gr::block,
             gr::basic_block, std::shared_ptr<mapper_muxer_phase3>>(
      m, "mapper_muxer_phase3", D(mapper_muxer_phase3))

      .def(py::init(&mapper_muxer_phase3::make), py::arg("nstrm"),
           py::arg("n_ofdm_syms"), py::arg("sd_num"), py::arg("use_polar"),
           py::arg("debug"), D(mapper_muxer_phase3, make))

      ;
}
