/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(mapper_muxer.h) */
/* BINDTOOL_HEADER_FILE_HASH(60bd8dfe9fb4e3b71b09af72cafb70a6) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/mapper_muxer.h>
// pydoc.h is automatically generated in the build directory
#include <mapper_muxer_pydoc.h>

void bind_mapper_muxer(py::module &m) {

  using mapper_muxer = ::gr::ncjt::mapper_muxer;

  py::class_<mapper_muxer, gr::block, gr::basic_block,
             std::shared_ptr<mapper_muxer>>(m, "mapper_muxer", D(mapper_muxer))

      .def(py::init(&mapper_muxer::make), py::arg("nstrm"), py::arg("modtype"),
           py::arg("n_ofdm_syms"), py::arg("sd_num"), py::arg("use_polar"),
           py::arg("code_rate"), py::arg("deterministic_input"),
           py::arg("debug"), D(mapper_muxer, make))

      ;
}
