/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(mc_stbc_decode.h) */
/* BINDTOOL_HEADER_FILE_HASH(9ed474ad010e959846720ed8cdd24424) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/mc_stbc_decode.h>
// pydoc.h is automatically generated in the build directory
#include <mc_stbc_decode_pydoc.h>

void bind_mc_stbc_decode(py::module &m) {

  using mc_stbc_decode = ::gr::ncjt::mc_stbc_decode;

  py::class_<mc_stbc_decode, gr::tagged_stream_block, gr::block,
             gr::basic_block, std::shared_ptr<mc_stbc_decode>>(
      m, "mc_stbc_decode", D(mc_stbc_decode))

      .def(py::init(&mc_stbc_decode::make), py::arg("fftsize"),
           py::arg("ndatasyms"), py::arg("npilotsyms"), py::arg("debug"),
           D(mc_stbc_decode, make))

      ;
}
