/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(mimo_detect.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7fde22103abe1d8fc8d0fa9d3797b78f) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/mimo_detect.h>
// pydoc.h is automatically generated in the build directory
#include <mimo_detect_pydoc.h>

void bind_mimo_detect(py::module &m) {

  using mimo_detect = ::gr::ncjt::mimo_detect;

  py::class_<mimo_detect, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<mimo_detect>>(m, "mimo_detect", D(mimo_detect))

      .def(py::init(&mimo_detect::make), py::arg("fftsize"), py::arg("nrx"),
           py::arg("nss"), py::arg("ndatasymbols"), py::arg("logfreq"),
           py::arg("debug"), D(mimo_detect, make))

      ;
}
