/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(mu_chanest.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(14d4c6bc7fe028c12b2e835f2442c07b) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/mu_chanest.h>
// pydoc.h is automatically generated in the build directory
#include <mu_chanest_pydoc.h>

void bind_mu_chanest(py::module &m) {

  using mu_chanest = ::gr::ncjt::mu_chanest;

  py::class_<mu_chanest, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<mu_chanest>>(m, "mu_chanest", D(mu_chanest))

      .def(py::init(&mu_chanest::make), py::arg("fftsize"), py::arg("ntx"),
           py::arg("nrx"), py::arg("nue"), py::arg("npreamblesyms"),
           py::arg("ndatasyms"), py::arg("mucpt") = false,
           py::arg("removecs") = false, py::arg("logfreq") = 10,
           py::arg("debug") = false, D(mu_chanest, make))

      ;
}
