/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(noair.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(aac55e3318c4adc5e31dbc2d352d5ce3) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/noair.h>
// pydoc.h is automatically generated in the build directory
#include <noair_pydoc.h>

void bind_noair(py::module &m) {

  using noair = gr::ncjt::noair;

  py::class_<noair, gr::block, gr::basic_block, std::shared_ptr<noair>>(
      m, "noair", D(noair))

      .def(py::init(&noair::make), py::arg("n_ofdm_syms"), py::arg("sc_num"),
           py::arg("pilot_sc_ind"), py::arg("frame_per_sec"), py::arg("snr_db"),
           py::arg("num_drop_init_packets"), py::arg("debug"), D(noair, make))

      ;
}
