/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(ofdm_mod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(de0e3b389bd6c33a6dbc2c2a0a4fd75d) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/ofdm_mod.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_mod_pydoc.h>

void bind_ofdm_mod(py::module &m) {

  using ofdm_mod = ::gr::ncjt::ofdm_mod;

  py::class_<ofdm_mod, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<ofdm_mod>>(m, "ofdm_mod", D(ofdm_mod))

      .def(py::init(&ofdm_mod::make), py::arg("rgmode"), py::arg("cplen"),
           py::arg("ntx"), py::arg("scaling"), D(ofdm_mod, make))

      ;
}
