/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(ofdm_demod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9d1462377b438bf28c38a46a51bd7d91) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/ofdm_demod.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_demod_pydoc.h>

void bind_ofdm_demod(py::module &m) {

  using ofdm_demod = ::gr::ncjt::ofdm_demod;

  py::class_<ofdm_demod, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<ofdm_demod>>(m, "ofdm_demod", D(ofdm_demod))

      .def(py::init(&ofdm_demod::make), py::arg("rgmode"), py::arg("cplen"),
           py::arg("symoffset") = 12, D(ofdm_demod, make))

      ;
}
