/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(p1_precoding.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e1c24a32ea7c35703adedf222ed8abaf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/p1_precoding.h>
// pydoc.h is automatically generated in the build directory
#include <p1_precoding_pydoc.h>

void bind_p1_precoding(py::module& m)
{

    using p1_precoding    = gr::ncjt::p1_precoding;


    py::class_<p1_precoding, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<p1_precoding>>(m, "p1_precoding", D(p1_precoding))

        .def(py::init(&p1_precoding::make),
           D(p1_precoding,make)
        )
        



        ;




}








