/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(pdc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(00b7e322be56670c49b520ec50178083) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/pdc.h>
// pydoc.h is automatically generated in the build directory
#include <pdc_pydoc.h>

void bind_pdc(py::module &m) {

  using pdc = gr::ncjt::pdc;

  py::class_<pdc, gr::block, gr::basic_block, std::shared_ptr<pdc>>(m, "pdc",
                                                                    D(pdc))

      .def(py::init(&pdc::make), py::arg("rgmode"), py::arg("combiner"),
           py::arg("num_copies"), py::arg("expire_ms"), py::arg("num_threads"),
           py::arg("deterministic_input"), py::arg("debug"), D(pdc, make))

      ;
}
