/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(pkt_err.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0f5f2310b32c5c53a095f2d4e95c5321) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/pkt_err.h>
// pydoc.h is automatically generated in the build directory
#include <pkt_err_pydoc.h>

void bind_pkt_err(py::module &m) {

  using pkt_err = ::gr::ncjt::pkt_err;

  py::class_<pkt_err, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<pkt_err>>(m, "pkt_err", D(pkt_err))

      .def(py::init(&pkt_err::make), py::arg("nstrms"), py::arg("filename"),
           py::arg("shortterm"), py::arg("avgwindow"), py::arg("logfreq") = 10,
           py::arg("logpkterr") = false, py::arg("debug") = false,
           D(pkt_err, make))

      ;
}
