/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(qam_demapper.h) */
/* BINDTOOL_HEADER_FILE_HASH(335ba231186271a51ea61d6e66405497) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/qam_demapper.h>
// pydoc.h is automatically generated in the build directory
#include <qam_demapper_pydoc.h>

void bind_qam_demapper(py::module &m) {

  using qam_demapper = ::gr::ncjt::qam_demapper;

  py::class_<qam_demapper, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<qam_demapper>>(m, "qam_demapper", D(qam_demapper))

      .def(py::init(&qam_demapper::make), py::arg("nstrms"), py::arg("modtype"),
           py::arg("usecsi") = false, py::arg("debug") = false,
           D(qam_demapper, make))

      ;
}
