/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(remapper_muxer.h) */
/* BINDTOOL_HEADER_FILE_HASH(69c1b6343fed28aaaa42f06bc5a4a065) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/remapper_muxer.h>
// pydoc.h is automatically generated in the build directory
#include <remapper_muxer_pydoc.h>

void bind_remapper_muxer(py::module &m) {

  using remapper_muxer = gr::ncjt::remapper_muxer;

  py::class_<remapper_muxer, gr::block, gr::basic_block,
             std::shared_ptr<remapper_muxer>>(m, "remapper_muxer",
                                              D(remapper_muxer))

      .def(py::init(&remapper_muxer::make), py::arg("phase"), py::arg("nstrm"),
           py::arg("n_ofdm_syms"), py::arg("sd_num"), py::arg("use_polar"),
           py::arg("debug"), D(remapper_muxer, make))

      ;
}
