/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(rg_demapper.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0997be2aa05c95179a963b2ef75418ee) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/rg_demapper.h>
// pydoc.h is automatically generated in the build directory
#include <rg_demapper_pydoc.h>

void bind_rg_demapper(py::module &m) {

  using rg_demapper = ::gr::ncjt::rg_demapper;

  py::class_<rg_demapper, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<rg_demapper>>(m, "rg_demapper", D(rg_demapper))

      .def(py::init(&rg_demapper::make), py::arg("fftsize"), py::arg("nstrm"),
           py::arg("framelen"), py::arg("ndatasyms"), py::arg("npilotsyms"),
           py::arg("nctrlsyms"), py::arg("datamodtype"), py::arg("ctrlmodtype"),
           py::arg("usecsi"), py::arg("debug"), D(rg_demapper, make))

      ;
}
