/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(rg_mapper.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f716424d7a4f3bd12dc516a101dcb3ae) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/rg_mapper.h>
// pydoc.h is automatically generated in the build directory
#include <rg_mapper_pydoc.h>

void bind_rg_mapper(py::module &m) {

  using rg_mapper = ::gr::ncjt::rg_mapper;

  py::class_<rg_mapper, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<rg_mapper>>(m, "rg_mapper", D(rg_mapper))

      .def(py::init(&rg_mapper::make), py::arg("nstrm"), py::arg("framelen"),
           py::arg("ndatasyms"), py::arg("npilotsyms"), py::arg("modtype"),
           py::arg("debug") = false, D(rg_mapper, make))

      ;
}
