/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(rx_mrc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(dc328f7a0357880a03ad1f5cf8979f48) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/rx_mrc.h>
// pydoc.h is automatically generated in the build directory
#include <rx_mrc_pydoc.h>

void bind_rx_mrc(py::module &m) {

  using rx_mrc = ::gr::ncjt::rx_mrc;

  py::class_<rx_mrc, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<rx_mrc>>(m, "rx_mrc", D(rx_mrc))

      .def(py::init(&rx_mrc::make), py::arg("fft_size"), py::arg("nrx"),
           py::arg("nsymbols"), py::arg("debug"), D(rx_mrc, make))

      ;
}
