/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(rx_sync.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2286487f00fe6b6abfbd7c4bed6289b7) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/rx_sync.h>
// pydoc.h is automatically generated in the build directory
#include <rx_sync_pydoc.h>

void bind_rx_sync(py::module &m) {

  using rx_sync = ::gr::ncjt::rx_sync;

  py::class_<rx_sync, gr::block, gr::basic_block, std::shared_ptr<rx_sync>>(
      m, "rx_sync", D(rx_sync))

      .def(
          py::init(&rx_sync::make), py::arg("nchans"), py::arg("npreamblesyms"),
          py::arg("ndatasyms"), py::arg("sampling_freq"), py::arg("pktspersec"),
          py::arg("acorr_thrd"), py::arg("xcorr_thrd"), py::arg("max_corr_len"),
          py::arg("gnbrx"), py::arg("debug") = false, D(rx_sync, make))

      ;
}
