/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(sic_detect.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9e74035d0313962e824826ad4e8f233a) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/sic_detect.h>
// pydoc.h is automatically generated in the build directory
#include <sic_detect_pydoc.h>

void bind_sic_detect(py::module &m) {

  using sic_detect = ::gr::ncjt::sic_detect;

  py::class_<sic_detect, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<sic_detect>>(m, "sic_detect", D(sic_detect))

      .def(py::init(&sic_detect::make), py::arg("fftsize"), py::arg("nrx"),
           py::arg("nss"), py::arg("modtype"), py::arg("ndatasymbols"),
           py::arg("debug"), D(sic_detect, make))

      ;
}
