/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(skip_data.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3ef389f41fe11eab8910afc1f5ebaf4a) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/skip_data.h>
// pydoc.h is automatically generated in the build directory
#include <skip_data_pydoc.h>

void bind_skip_data(py::module &m) {

  using skip_data = ::gr::ncjt::skip_data;

  py::class_<skip_data, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<skip_data>>(m, "skip_data", D(skip_data))

      .def(py::init(&skip_data::make), py::arg("nstrm"), py::arg("skiplen"),
           py::arg("debug") = false, D(skip_data, make))

      ;
}
