/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(soft_demapper.h) */
/* BINDTOOL_HEADER_FILE_HASH(655259e087aa2bbde55b537a845cecaf) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/soft_demapper.h>
// pydoc.h is automatically generated in the build directory
#include <soft_demapper_pydoc.h>

void bind_soft_demapper(py::module &m) {

  using soft_demapper = ::gr::ncjt::soft_demapper;

  py::class_<soft_demapper, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<soft_demapper>>(m, "soft_demapper",
                                             D(soft_demapper))

      .def(py::init(&soft_demapper::make), py::arg("nstrm"),
           py::arg("framelen"), py::arg("modtype"), py::arg("usecsi"),
           py::arg("debug"), D(soft_demapper, make))

      ;
}
