/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(srsran_ldpc_decoder.h) */
/* BINDTOOL_HEADER_FILE_HASH(a1675b1c1176da99c4a48b9a016db3d7) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/srsran_ldpc_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <srsran_ldpc_decoder_pydoc.h>

void bind_srsran_ldpc_decoder(py::module &m) {

  using srsran_ldpc_decoder = ::gr::ncjt::srsran_ldpc_decoder;

  py::class_<srsran_ldpc_decoder, gr::tagged_stream_block, gr::block,
             gr::basic_block, std::shared_ptr<srsran_ldpc_decoder>>(
      m, "srsran_ldpc_decoder", D(srsran_ldpc_decoder))

      .def(py::init(&srsran_ldpc_decoder::make), py::arg("mod_order"),
           py::arg("message_length"), py::arg("codeword_length"),
           py::arg("is_output_byte"), py::arg("debug"),
           D(srsran_ldpc_decoder, make))

      ;
}
