/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(stream_mapper.h) */
/* BINDTOOL_HEADER_FILE_HASH(6f4c1748da141cd04e41e35553da295f) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/stream_mapper.h>
// pydoc.h is automatically generated in the build directory
#include <stream_mapper_pydoc.h>

void bind_stream_mapper(py::module &m) {

  using stream_mapper = ::gr::ncjt::stream_mapper;

  py::class_<stream_mapper, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<stream_mapper>>(m, "stream_mapper",
                                             D(stream_mapper))

      .def(py::init(&stream_mapper::make), py::arg("rgmode"), py::arg("nstrm"),
           py::arg("phase1_modtype"), py::arg("phase2_modtype"),
           py::arg("phase3_modtype"), py::arg("code_rate"),
           py::arg("deterministic_input"), py::arg("debug"),
           D(stream_mapper, make))

      ;
}
