/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(sync_all.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ab0e2942f484f68b65e0a01dbf5bfa3b) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/sync_all.h>
// pydoc.h is automatically generated in the build directory
#include <sync_all_pydoc.h>

void bind_sync_all(py::module &m) {

  using sync_all = ::gr::ncjt::sync_all;

  py::class_<sync_all, gr::block, gr::basic_block, std::shared_ptr<sync_all>>(
      m, "sync_all", D(sync_all))

      .def(py::init(&sync_all::make), py::arg("num_rx"),
           py::arg("debug") = false, D(sync_all, make))

      ;
}
