/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(tx_frm_ctrl.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(21d4df7c140e0b021af162015b72b03e) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/tx_frm_ctrl.h>
// pydoc.h is automatically generated in the build directory
#include <tx_frm_ctrl_pydoc.h>

void bind_tx_frm_ctrl(py::module &m) {

  using tx_frm_ctrl = ::gr::ncjt::tx_frm_ctrl;

  py::class_<tx_frm_ctrl, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<tx_frm_ctrl>>(m, "tx_frm_ctrl", D(tx_frm_ctrl))

      .def(py::init(&tx_frm_ctrl::make), py::arg("ntx"), py::arg("ndatasyms"),
           py::arg("filename"), py::arg("samplerate"), py::arg("pktspersec"),
           py::arg("starttime"), py::arg("padding"), py::arg("autostart"),
           py::arg("delay"), py::arg("debug"), D(tx_frm_ctrl, make))

      ;
}
