/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(tx_framing.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b865b30c62cd56cb021054043bf30bfc) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/tx_framing.h>
// pydoc.h is automatically generated in the build directory
#include <tx_framing_pydoc.h>

void bind_tx_framing(py::module &m) {

  using tx_framing = ::gr::ncjt::tx_framing;

  py::class_<tx_framing, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<tx_framing>>(m, "tx_framing", D(tx_framing))

      .def(py::init(&tx_framing::make), py::arg("ntx"), py::arg("ndatasyms"),
           py::arg("filename"), py::arg("fs"), py::arg("pktspersec"),
           py::arg("starttime"), py::arg("padding"), py::arg("csirs") = false,
           py::arg("debug") = false, D(tx_framing, make))

      ;
}
