/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(udp_video_pub.h) */
/* BINDTOOL_HEADER_FILE_HASH(22a864b4d408eda961765c0d7f2e5d83) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/udp_video_pub.h>
// pydoc.h is automatically generated in the build directory
#include <udp_video_pub_pydoc.h>

void bind_udp_video_pub(py::module &m) {

  using udp_video_pub = gr::ncjt::udp_video_pub;

  py::class_<udp_video_pub, gr::block, gr::basic_block,
             std::shared_ptr<udp_video_pub>>(m, "udp_video_pub",
                                             D(udp_video_pub))

      .def(py::init(&udp_video_pub::make), py::arg("grp"), py::arg("port"),
           D(udp_video_pub, make))

      ;
}
