/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(ul_precoding_offline.h) */
/* BINDTOOL_HEADER_FILE_HASH(7f84493d3247fd6450ec69c9eb6c9f80) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/ul_precoding_offline.h>
// pydoc.h is automatically generated in the build directory
#include <ul_precoding_offline_pydoc.h>

void bind_ul_precoding_offline(py::module &m) {

  using ul_precoding_offline = ::gr::ncjt::ul_precoding_offline;

  py::class_<ul_precoding_offline, gr::tagged_stream_block, gr::block,
             gr::basic_block, std::shared_ptr<ul_precoding_offline>>(
      m, "ul_precoding_offline", D(ul_precoding_offline))

      .def(py::init(&ul_precoding_offline::make), py::arg("nss"),
           py::arg("ul_ntx"), py::arg("dl_ntx"), py::arg("dl_nrx"),
           py::arg("numhtsyms"), py::arg("numdatasyms"),
           py::arg("numprecodedsyms"), py::arg("eigenmode"),
           py::arg("filename"), py::arg("debug"), D(ul_precoding_offline, make))

      ;
}
