/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(video_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8297a07e95e8a8fd821a391df0d7021c) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/video_sink.h>
// pydoc.h is automatically generated in the build directory
#include <video_sink_pydoc.h>

void bind_video_sink(py::module &m) {

  using video_sink = ::gr::ncjt::video_sink;

  py::class_<video_sink, gr::tagged_stream_block, gr::block, gr::basic_block,
             std::shared_ptr<video_sink>>(m, "video_sink", D(video_sink))

      .def(py::init(&video_sink::make), py::arg("framelen"),
           py::arg("debug") = false, D(video_sink, make))

      ;
}
