/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(video_source.h) */
/* BINDTOOL_HEADER_FILE_HASH(95d4e256f78aff8c6237cda1ca4cca12) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncjt/video_source.h>
// pydoc.h is automatically generated in the build directory
#include <video_source_pydoc.h>

void bind_video_source(py::module &m) {

  using video_source = ::gr::ncjt::video_source;

  py::class_<video_source, gr::block, gr::basic_block,
             std::shared_ptr<video_source>>(m, "video_source", D(video_source))

      .def(py::init(&video_source::make), py::arg("framelen"), py::arg("debug"),
           D(video_source, make))

      ;
}
